#!/usr/bin/env bash
set -euo pipefail

# ─── Creates .env.local in every app from a shared template ───────────────────
# Usage:  ./scripts/setup-local-env.sh
#
# You'll be prompted for values that differ per app (LIFF IDs).
# Shared values (API_URL, LOGIN_URL) are set to localhost defaults automatically.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APPS=("portal" "wounds" "supplements" "bones" "intimacy" "hq")

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Vitera Local Dev Environment Setup                         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This will create .env.local in each app directory."
echo "Leave LIFF IDs blank to skip LINE login locally."
echo ""

read -rp "LIFF ID for wounds    (or blank): " LIFF_WOUNDS
read -rp "LIFF ID for supplements (or blank): " LIFF_SUPPLEMENTS
read -rp "LIFF ID for bones     (or blank): " LIFF_BONES
read -rp "LIFF ID for intimacy  (or blank): " LIFF_INTIMACY
echo ""

get_liff_id() {
  case "$1" in
    wounds)      echo "$LIFF_WOUNDS" ;;
    supplements) echo "$LIFF_SUPPLEMENTS" ;;
    bones)       echo "$LIFF_BONES" ;;
    intimacy)    echo "$LIFF_INTIMACY" ;;
    *)           echo "" ;;
  esac
}

for app in "${APPS[@]}"; do
  dest="$REPO_ROOT/apps/$app/.env.local"
  liff_id="$(get_liff_id "$app")"

  cat > "$dest" << EOF
# Local dev — generated by scripts/setup-local-env.sh
NEXT_PUBLIC_API_URL=http://localhost:8080
NEXT_PUBLIC_LOGIN_URL=http://localhost:3000/login
NEXT_PUBLIC_PORTAL_URL=http://localhost:3000
NEXT_PUBLIC_ALLOWED_REDIRECT_ORIGINS=http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004,http://localhost:3005
NEXT_PUBLIC_LIFF_ID=${liff_id}
EOF

  echo "✅ apps/$app/.env.local created"
done

echo ""
echo "Done! Start development with:"
echo "  pnpm dev           # all apps"
echo "  pnpm dev:wounds    # wounds + portal + backend"
